# Generated by Django 3.2.4 on 2021-06-14 16:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_text', models.CharField(max_length=200)),
                ('search_date', models.DateTimeField(verbose_name='date de recherche')),
                ('associated_clicks', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), size=None)),
            ],
        ),
    ]
